config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'
require 'subdomain_constraint'
require 'user_role_constraint'

Sidekiq::Web.app_url = '/'

Rails.application.routes.draw do
  mount API::Base => '/'
  mount GrapeSwaggerRails::Engine => '/documentation'

  get '/auth/google_user/callback', to: 'omniauth#create'
  get '/auth/*_student/callback', to: 'students/omniauth#create'
  scope constraints: SubdomainConstraint.new('admin', 'teach', 'school') do
    devise_for :users,
               controllers: { registrations: 'registrations', sessions: 'sessions' },
               path_names: { registration: 'register' }
  end
  mount Shrine.upload_endpoint(:cache) => '/upload', as: :upload

  scope constraints: SubdomainConstraint.new('teach') do
    scope module: :teach do
      get '/', to: 'lessons#index'
    end
    namespace :teach, path: '' do
      get '/dashboard', to: 'lessons#index', as: :dashboard
      resources :lessons do
        collection do
          get :draft
          get :pending
          get :approved
          get :published
          get :reviewable
          get :search
        end
        member do
          get :review
          post :publish
          post :status
          post :unpublish

          # TODO: move next 2 methods to separate controller
          post :add_objective
          post :set_color
          delete :remove_objective

          resource :lesson_split, only: [:new, :create]
          resource :task_move, only: [:new, :create]
        end
        resources :tasks do
          member do
            patch :position
            patch :toggle_published
            delete :delete_file_attachment
            get :convert_text_task_type, as: 'convert_type'
          end
        end
        resources :phrases, only: %i[index create destroy] do
          collection do
            post :generate
            delete :destroy_batch
          end
        end
        resources :reviews, only: %i[index create destroy]
      end

      resources :tasks do
        resources :items, only: %i[index create destroy update] do
          resources :words, only: %i[index create destroy]

          member do
            patch :move_up
            patch :move_down
          end
        end
      end
      scope module: :tasks, path: 'tasks/:task_id', as: :task do
        resource :preview, only: :show
      end

      resources :items, only: [] do
        resources :options, only: %i[create update destroy] do
          put :toggle_correct, on: :member
        end
      end

      resource :current_team, only: :create
      resources :teams, only: %i[new create edit update destroy] do
        member do
          post :default
          get :followers
          get :instruction
          post 'instruction' => 'teams#instruction_post'
        end

        resources :team_users, path: 'members', only: %i[index update destroy] do
          member do
            delete :leave
          end
        end

        resources :team_domains, only: %i[create destroy]
      end

      resources :posts
      resources :courses do
        get :words, on: :member
        resources :course_sections, as: :sections, only: %i[create update destroy] do
          member do
            post :add_lesson
            get :remove_lesson
            patch :move_up
            get :move_up_lesson
            get :move_down_lesson
          end
        end
      end
    end
  end
  resource :profile, only: %i[show update] do
    patch :update_password
    get :incomplete
  end

  scope constraints: SubdomainConstraint.new('admin') do
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
    scope module: :admin do
      get '/', to: 'dashboard#index'
    end
    namespace :admin, path: '' do
      scope constraints: UserRoleConstraint.new(:admin, :editor) do
        resources :dashboard, only: :index
        resources :lessons, only: %i[index edit update show]
        resources :courses, only: %i[index show] do
          member do
            get :words
            get :level_words
            put :translate_words
          end

          collection do
            get :reset_phrases_count
          end
        end
        resources :skills, only: %i[index create show update]
        resources :teams, except: :destroy
        resources :users
        resources :students
        resources :rewards
        resources :crawlers
        resources :search, only: :index
        resources :languages, only: [:index, :edit, :update] do
          get :inactive, on: :collection
          post :add_character, on: :member
          delete :remove_character, on: :member
          scope module: 'dictionary/languages' do
            resources :words do
              collection do
                delete :destroy_multiple
                get :remove_from_collection
                get :csv_import
                post 'csv_import' => 'words#csv_import_post'
                post :text_import
                post :recalculate_frequency
                get :search
                get :add_to_collection
                post 'add_to_collection' => 'words#add_to_collection_post'
              end

              member do
                get :edit_translation
                put :update_translation
              end
            end
            resources :collections do
              put :translate_words, on: :member
            end
          end
        end
        resources :teams do
          scope module: 'teams' do
            scope module: 'oauth', path: '' do
              resources :apps, path: 'oauth_apps', only: [:index, :show, :update, :destroy], as: :oauth_apps do
                put :regenerate_key, on: :member
              end
            end
          end

          member do
            post :signin_school
          end
        end
        resources :plans
      end
      match '/*any', via: :all, to: redirect(subdomain: 'teach', path: '/')
    end
  end
  resource :profile, only: %i[show update] do
    patch :update_password
  end

  scope constraints: SubdomainConstraint.new('school') do
    scope module: :school do
      get '/', to: 'dashboard#index'
    end

    namespace :school, path: '' do
      get '/dashboard', to: 'dashboard#index', as: :dashboard
      resource :gdpr_agreement, only: :show
      resource :dashboard, only: :index do
        collection do
          post :agreement
        end
      end
      resource :current_team, only: [:create, :edit, :update] do
        get :set, as: :set_team, to: 'current_teams#create'
      end
      resources :team_students, as: :students, except: [:create] do
        member do
          get :archive
          post :assign_team_group
          get :move_class
          delete :revoke_team_group
          get :lessons
          get :search_lessons
          post :assign_lessons
          get :restore_student
          get :remove_student
          get :courses
          get :build_language
          get :remove_language
          get :assign_course
          post :assign_course
        end

        collection do
          get :archived_students
          get :clear_archive
          get :import_students
          post :analyze_imported_file
          post :create_batch
          get  :invite_students
          post :send_invitations
          get :available_languages
        end

        resources :activities
      end
      post 'school_students', to: 'team_students#create', as: 'create_students'
      resources :team_groups do
        member do
          get :edit_plan
          put :archive
          put :update_plan
          get :toggle_joinable
          get :assign_course
          post :assign_course
        end
      end
      resources :team_users do
        member do
          get :activities
        end
        collection do
          get  :import_team_users
          post :analyze_imported_file
          post :create_batch
        end
      end
      resources :team_students, only: [] do
        resources :licenses, only: [:create, :update, :destroy] do
          collection do
            get :revoke_license
          end
          put :remove_end_date, on: :member
        end
      end
      resources :lessons
      resources :assignments, as: :documents
      resources :comments do
        post :add_comments, on: :member
        post :document_content_update, on: :collection
      end
      resources :school_assignments, as: :assignments do
        member do
          get :assign_student
          post 'assign_student' => 'school_assignments#assign_student_post'
          get :review
        end
      end
      resources :tests
      resources :activities do
        collection do
          get :activity_logs
        end
        member do
          put :undo_activity
        end
      end
      resources :oauth_apps do
        member do
          put :refresh_secret
        end
      end
      resource :user, only: [:edit, :update], as: :current_profile
      resources :courses, only: [:index, :show] do
        member do
          get :assign_team_group
          post :assign_team_group
        end
        resources :course_sections, only: :show do
          member do
            get :change_view_mode
          end
        end
      end
      get 'search', to: 'search#index', as: :search
      get 'mobile', to: 'mobile#index', as: :mobile
    end
  end

  resources :teams, only: [] do
    resource :team_invitations, path: 'join'
  end

  resources :team_domain_invitations, only: [] do
    patch :accept
    patch :decline
  end

  devise_for :students
  root to: 'students/lessons#index'
  namespace :students, path: '' do
    scope path: 'invitation/:team_id' do
      resource :invitations, path: '', as: :invitation, only: :show do
        post :join, on: :member
      end
    end
    resources :courses, only: %i[show]
    resources :lessons do
      member do
        get 'play(/*any)' => '/static#index'

app/controllers/school/activities_controller.rb
# frozen_string_literal: true

module School
  class ActivitiesController < ApplicationController
    def index
      authorize_action
      if params[:student_id].present?
        activities = Activity.by_team_student(team_student).page(params[:page])
        render :student_activities, locals: { student: student, activities: activities }
      else
        activities = Activity.by_team_user(team_user).page(params[:page])
        render :team_user_activities, locals: { team_user: team_user, activities: activities }
      end
    end

    def activity_logs
      authorize_action
      collection = Activity.by_team(current_team.id).includes(:owner, :recipient, :trackable).distinct.page(params[:page])
      @search = collection.ransack(params[:q])
      render :activity_logs, locals: { activities: @search.result, owners: current_team.team_users }
    end

    def undo_activity
      authorize_action(activity)
      result = School::UndoActivityService.call(current_team: current_team, activity: activity, current_user: current_user)
      if result[:errors].blank?
        redirect_to activity_logs_school_activities_path
      else
        redirect_to activity_logs_school_activities_path, notice: result[:errors][0]
      end
    end

    private

    def activity
      @activity ||= Activity.find(params[:id])
    end

    def student
      @student ||= Student.find(params[:student_id])
    end

    def team_user
      @team_user ||= TeamUser.find(params[:team_user_id])
    end

    def team_student(current_student = student)
      current_team.team_students.find_by(student: current_student)
    end
    helper_method :team_student

    def authorize_action(record = Activity)
      authorize(record, "#{action_name}?", policy_class: policy_class)
    end

    def policy_class
      School::ActivityPolicy
    end
  end
end

app/controllers/school/application_controller.rb
# frozen_string_literal: true

module School
  class ApplicationController < ::ApplicationController
    include PasswordGenerator
    include UserControllerContext
    include IncompleteProfileChecker
    before_action :authenticate_user!

    layout 'school/school'

    def policy(record)
      super([:school, record])
    end

    def pundit_user
      current_team_user
    end

    def current_team_user
      return if current_user.blank? || current_team.blank?

      @current_team_user ||= current_user.team_users.find_by(team_id: current_team&.id)
    end
    helper_method :current_team_user

    def redirect_onboarding(team = current_team)
      return if team.abilities.present?
      return unless current_team_user.owner?

      redirect_to instruction_teach_team_path(team, refer: request.referer)
    end

    def gdpr_consented?
      render 'school/shared/gdpr_consenter' unless current_team.gdpr_consented?
      current_team.gdpr_consented?
    end
  end
end

app/controllers/school/assignments_controller.rb
# frozen_string_literal: true

module School
  class AssignmentsController < ApplicationController
    def index
      authorize_action
      @search = scope.ransack(params[:q])
      assignments_stats = AssignmentsStats.stats(scope, current_team)
      render :index, locals: { documents: @search.result, assignments_stats: assignments_stats }
    end

    def show
      authorize_action(document)
      comment = comment_scope.new(commentable: document)
      render :show, locals: { document: document, comment: comment, comments: document.comments.order(created_at: :asc) }
    end

    private

    def scope
      policy_scope(document_scope, policy_scope_class: School::AssignmentPolicy::Scope)
    end

    def document_scope
      Document.where(team: current_team)
    end

    def document
      @document = Document.find(params[:id])
    end

    def comment_scope
      current_user.comments
    end

    def policy_class
      School::AssignmentPolicy
    end

    def authorize_action(record = Student)
      authorize(record, "#{action_name}?", policy_class: policy_class)
    end
  end
end

app/controllers/school/comments_controller.rb
# frozen_string_literal: true

module School
  class CommentsController < ApplicationController
    def create
      comment = comments_scope.where(commentable: document).new(comment_params)
      if comment.save
        document.reviewed!
        School::DocumentMailer.with(comment: comment).new_document_comment.deliver_later
        render :create, locals: { comment: comment, document: document }
      else
        render 'school/assignments/show', locals: { document: document, comment: comment }
      end
    end

    def add_comments
      comment.comments[params[:word]] = params[:comment]
      comment.save
      render :add_comments, locals: { word: params[:word], comment: params[:comment], document_id: params[:document_id] }
    end

    def document_content_update
      document.update(comment_contents: params[:content])
      render json: { success: true }
    end

    private

    def policy_class
      School::CommentPolicy
    end

    def authorize_action(record = Comment)
      authorize(record, "#{action_name}?", policy_class: policy_class)
    end

    def comment
      @comment ||= Comment.find(params[:id])
    end

    def document
      @document ||= Document.find(params[:document_id])
    end

    def comments_scope
      current_user.comments
    end

    def comment_params
      params.require(:comment).permit(:content, :audio)
    end
  end
end

app/controllers/school/course_sections_controller.rb
# frozen_string_literal: true

module School
  class CourseSectionsController < ApplicationController
    layout 'school/empty'

    def show
      authorize_action
      render_show
    end

    def change_view_mode
      authorize_action
      current_user.update(table_view: params[:table_view_mode])
      render_show
    end

    def render_show
      render :show, locals: {
        course: course,
        course_section: course_section,
        lessons: lessons,
        table_view: current_user_table_view
      }
    end

    private

    def lessons
      course_section.lessons.kept.published
    end

    def current_user_table_view
      current_user.table_view.presence || 'list'
    end

    def course_section
      @course_section ||= scope.find(params[:id])
    end

    def course
      course_section.course
    end

    def authorize_action(record = Course)
      authorize(record, "#{action_name}?", policy_class: policy_class)
    end

    def policy_class
      School::CourseSectionPolicy
    end

    def scope
      policy_scope(CourseSection, policy_scope_class: School::CourseSectionPolicy::Scope)
    end
  end
end

app/helpers/school/activities_helper.rb
# frozen_string_literal: true

module School
  module ActivitiesHelper
    def undo_activity_message(activity) # rubocop:disable all
      case activity.key
      when Activity::EVENT_TYPES[:license_created]
        return unless activity.recipient&.active_license

        undo_image + t('activerecord.attributes.activity.undo.revoke_license')
      when Activity::EVENT_TYPES[:license_updated]
        return unless activity.recipient&.active_license

        undo_image + t('activerecord.attributes.activity.undo.remove_end_date')
      when Activity::EVENT_TYPES[:license_revoked]
        return if activity.recipient&.active_license

        undo_image + t('activerecord.attributes.activity.undo.reassign_license')
      when Activity::EVENT_TYPES[:team_student_archived]
        return unless activity.trackable&.archived_at

        undo_image + t('activerecord.attributes.activity.undo.unarchive_student')
      end
    end

    def undo_image
      image_tag('icons/undo.svg', class: 'mr-2')
    end
  end
end

app/views/school/current_teams/_api_access_profile.html.slim
.apps-header.mb-3
  h3 = t('school.profile.api_access.integrate_services')
  p.mt-3 = t('school.profile.api_access.give_students_access')
  p
    = t('school.profile.api_access.create_app')
    = link_to t('school.profile.api_access.documentation'), nil, class: 'ml-1 mr-1'
    = t('school.profile.api_access.to_start_your_process')
.apps-content
  - team.oauth_apps.each do |oauth_app|
    = form_tag school_oauth_app_path(oauth_app), method: :put, remote: true, class: 'oauth-app-form'
      .remove-app-field
        = link_to school_oauth_app_path(oauth_app), method: :delete, remote: true, data: {confirm: t('school.profile.api_access.delete_confirm')} do
          i.fas.fa-times
      .mb-2
        = label_tag 'name', t('school.profile.api_access.app_name')
        = text_field_tag 'name', oauth_app.name, class: 'form-control', autocomplete: 'off', required: true
      .mb-3
        = label_tag 'redirect_uris[]', t('school.profile.api_access.redirect_url')
        = text_field_tag 'redirect_uris[]', oauth_app.redirect_uris[0], class: 'form-control', autocomplete: 'off', required: true
      .mb-2.d-flex.align-items-center.secret-form
        = text_field_tag 'secret', oauth_app.secret, class: 'form-control secret-field', autocomplete: 'off', required: true
        = link_to refresh_secret_school_oauth_app_path(oauth_app), class: 'sync-link', method: :put, remote: true do
          i.fas.fa-sync
        button.btn.btn-primary.ml-2.copy-link-btn data-action="click->school-profile#copySecretCode"
          = t('admin.team_users.team_link.copy')
      .mb-1.text-center
        = submit_tag t('common.buttons.save'), class: 'btn btn-primary'
= form_tag school_oauth_apps_path, method: :post, remote: true
  .oauth-app-form
    .mb-2
      = label_tag 'name', t('school.profile.api_access.app_name')
      = text_field_tag 'name', '', class: 'form-control', autocomplete: 'off', required: true
    .mb-3
      = label_tag 'redirect_uris[]', t('school.profile.api_access.redirect_url')
      = text_field_tag 'redirect_uris[]', '', class: 'form-control', autocomplete: 'off', required: true
    .mb-2.d-flex.align-items-center.secret-form
      = text_field_tag 'secret', '', class: 'form-control secret-field', autocomplete: 'off', required: true
      button.btn.btn-primary.ml-2.copy-link-btn data-action="click->school-profile#copySecretCode"
        = t('admin.team_users.team_link.copy')
  button.btn.btn-cancel.btn-lg.app-save-btn type="submit"
    i.fas.fa.fa-plus.mr-2
    = t('school.profile.api_access.add_new_app')

app/views/school/current_teams/_billing_profile.html.slim
= form_tag school_current_team_path, method: :put, remote: true
  .mb-5
    = label_tag 'business_registration_id', t('school.profile.billing.business_registration_id')
    = text_field_tag 'business_registration_id', team.business_registration_id, class: 'form-control', autocomplete: 'off', required: true
  .mb-2
    = label_tag 'street_address', t('school.profile.billing.street_address')
    = text_field_tag 'street_address', team.street_address, class: 'form-control', autocomplete: 'off', required: true
  .d-flex.justify-content-between.mb-2
    .postal-code-field
      = label_tag 'postal_code', t('school.profile.billing.postal_code')
      = text_field_tag 'postal_code', team.postal_code, class: 'form-control', autocomplete: 'off', required: true
    .city-field.mr-2
      = label_tag 'city', t('school.profile.billing.city')
      = text_field_tag 'city', team.city, class: 'form-control', autocomplete: 'off', required: true
  .d-flex.justify-content-between.mb-2
    .country-field.w-50.mr-2
      = label_tag 'country', t('school.profile.billing.country')
      = select_tag 'country', options_for_select(ISO3166::Country.all.sort.map{|country| [[country.name, country.emoji_flag].join(', '), country.alpha2]}, team.country), class: 'form-control', data: { target: "school-profile.selectCountry", placeholder: t('school.profile.billing.country') }, prompt: 'Select'
      .state-field
      = label_tag 'state', t('school.profile.billing.state')
      = select_tag 'state', options_for_select([], team.state), class: 'form-control state-select', data: { target: "school-profile.selectState" }
  = submit_tag t('common.buttons.save'), class: 'btn btn-primary float-right mt-3'

- countryData = ISO3166::Country.all.sort.map{|country| [country.alpha2, country.states.map{|state| [state[0], state[1].name] }]}

javascript:
  window.countryData = { countries: #{countryData.to_json.html_safe}, by_ip: "#{country_by_ip}", current_country:  "#{team.country}", current_state: "#{team.state}" }

app/views/school/current_teams/_general_profile.html.slim
= form_tag school_current_team_path, method: :put, remote: true
  .mb-3 data-target = "school-profile.body"
    = label_tag 'logo-image', t('teach.lessons.form.team_image')
    .d-flex.justify-content-end.align-items-center.upload-container data-upload-container="true"
      .image-preview.flex-grow-1 data-upload-preview-container="true" data-target='school-profile.preview'
        - if team.image_url
          = image_tag(team.image_url(:brand) || team.image_url, class: 'preview')
      .upload-image-field.mr-2
        = hidden_field_tag 'image', '', "data-upload-hidden" => "true"
        a.upload-action-button.align-self-center.mr-2 data-upload-trigger="true"
          = t('school.users.form.upload_image')
      = file_field_tag nil, accept: "image/svg+xml,image/png", "data-upload" => "image", class: "upload-file"
      .remove-action-field.d-flex.align-items-center data-upload-remove-trigger="true"
        = check_box_tag 'remove_image', '1', team.remove_image, class: 'mr-2'
        = label_tag 'remove_image', t('school.profile.general.remove_image'), class: 'remove-action-button'
  .d-flex.justify-content-between.mb-2
    .name-field.w-50.mr-3
      = label_tag 'name', t('activerecord.attributes.team.name')
      = text_field_tag 'name', team.name, class: 'form-control', autocomplete: 'off', required: true
    .language-field.w-50
      = label_tag 'default_language_id', t('.select_default_school_language')
      = select_tag 'default_language_id', options_for_select(Language.active.map { |e| [asset_path("flags/#{language_to_flag_code(e.code)}.svg").to_s + ', ' + e.name.strip, e.id]}, team.default_language_id),
              class: 'form-control',
              data: { target: 'school-profile.selectLanguage', placeholder: t('profiles.profile_form.select_default_language') },
              prompt: ''
  = submit_tag t('common.buttons.save'), class: 'btn btn-primary float-right mt-3'

app/views/school/current_teams/_privacy_profile.html.slim
= form_tag school_current_team_path, method: :put, remote: true
  .mb-3
    = label_tag 'privacy_url', t('school.profile.privacy.privacy_url')
    = text_field_tag 'privacy_url', team.privacy_url, class: 'form-control', autocomplete: 'off', required: true
  .mb-3
    = label_tag 'gdpr_contact_name', t('school.profile.privacy.gdpr_contact_name')
    = text_field_tag 'gdpr_contact_name', team.gdpr_contact_name, class: 'form-control', autocomplete: 'off', required: true
  .mb-3
    = label_tag 'destroy_user_data_after', t('school.profile.privacy.destroy_user_after')
    = text_field_tag 'destroy_user_data_after', team.destroy_user_data_after || 365, class: 'form-control', autocomplete: 'off', required: true
  .mb-5.text-right
    = submit_tag t('common.buttons.save'), class: 'btn btn-primary'
  .gdpr-agreement
    h5= t('school.profile.privacy.data_processor_agreement')
    = link_to team.gdpr_agreement_url, class: 'd-inline-flex align-items-center font-weight-bold ml-3' do
      = image_tag('icons/download.svg', class: 'mr-1')
      = t('school.profile.privacy.download_signed_agreement')

app/views/school/current_teams/_profile_form.html.slim
.modal-dialog.modal-dialog-centered.school-profile-modal role="document" data-controller="school-profile"
  .modal-content
    .d-flex
      .profile-sidebar
        h3.profile-title = t('layouts.school.sidebar.school_settings')
        ul.nav.flex-column.mb-3 role="tablist"
          li.nav-item
            a.nav-link.active#general-tab data-toggle="pill" href="#general-panel" role="tab" aria-controls="general-panel" aria-selected="true"
              = t('school.teachers.new.general')
          li.nav-item.d-flex.justify-content-between.align-items-baseline
            a.nav-link#tests-tab data-toggle="pill" href="#tests-panel" role="tab" aria-controls="tests-panel" aria-selected="false"
              = t('layouts.school.sidebar.tests')
            - unless team.lingutest_enabled
              span.ml-2.status-badge = t('school.profile.tests.disabled').upcase
          li.nav-item
            a.nav-link#billing-tab data-toggle="pill" href="#billing-panel" role="tab" aria-controls="billing-panel" aria-selected="false"
              = t('school.profile.billing.title')
          li.nav-item
            a.nav-link#api-access-tab data-toggle="pill" href="#api-access-panel" role="tab" aria-controls="api-access-panel" aria-selected="false"
              = t('school.profile.api_access.title')
          li.nav-item
            a.nav-link#privacy-tab data-toggle="pill" href="#privacy-panel" role="tab" aria-controls="privacy-panel" aria-selected="false"
              = t('school.profile.privacy.title')
          li.nav-item
            a.nav-link#subcontractors-tab data-toggle="pill" href="#subcontractors-panel" role="tab" aria-controls="subcontractors-panel" aria-selected="false"
              = t('school.gdpr_agreements.gdpr_subcontractors.sub-contractors_heading')
      .profile-content
        .close-button
          button.close.text-right.mr-3.mt-3 type="button" data-dismiss="modal" aria-label="Close"
            span.font-weight-light aria-hidden="true" == ("&times")
        .tab-content
          .tab-pane.fade.show.active#general-panel role="tabpanel" aria-labelledby="general-tab"
            = render 'general_profile', team: team
          .tab-pane.fade#tests-panel role="tabpanel" aria-labelledby="tests-tab"
            = render 'tests_profile', team: team
          .tab-pane.fade#billing-panel role="tabpanel" aria-labelledby="billing-tab"
            = render 'billing_profile', team: team, country_by_ip: country_by_ip
          .tab-pane.fade#api-access-panel role="tabpanel" aria-labelledby="api-access-tab"
            = render 'api_access_profile', team: team
          .tab-pane.fade#privacy-panel role="tabpanel" aria-labelledby="privacy-tab"
            = render 'privacy_profile', team: team
          .tab-pane.fade#subcontractors-panel role="tabpanel" aria-labelledby="subcontractors-tab"
            = render 'school/gdpr_agreements/gdpr_subcontractors'

app/views/school/current_teams/_tests_profile.html.slim
= form_tag school_current_team_path, method: :put, remote: true, class: 'text-center'
  - if team.lingutest_enabled
    .my-2= image_tag("lingutest_logo.svg", width: 200, height: 160)
    .mb-4.pl-3.test-module-toggle
      h4 = t('school.profile.tests.test_module')
      = hidden_field_tag 'lingutest_enabled', true, data: { target: 'school-profile.enabledTest' }
      .form-group
        .custom-control.custom-switch
          = check_box_tag :lingutest_enabled_check, '1', team.lingutest_enabled, class: 'custom-control-input', data: { action: 'change->school-profile#enabledTestChanged', on: t('school.profile.tests.enabled'), off: t('school.profile.tests.disabled') }
          = label_tag :lingutest_enabled_check, t('school.profile.tests.enabled'), class: 'custom-control-label', data: { target: 'school-profile.enabledTestCheck' }
    .mb-3.enable-test-note.pl-3.text-left
      p.mb-3= t('school.profile.tests.enable_test_note')
      p
        = t('school.profile.tests.pay_note')
        =< t('school.profile.tests.service_provider_note')
    = submit_tag t('common.buttons.save'), class: 'btn btn-primary float-right'
  - else
    .mt-2.mb-2= image_tag("lingutest_logo.svg", width: 200, height: 160)
    .mb-3.enable-test-note
      p.mb-3= t('school.profile.tests.enable_test_note')
      p
        = t('school.profile.tests.pay_note')
        =< t('school.profile.tests.service_provider_note')
    .agree-testing-service.d-flex.justify-content-center.align-items-center.mb-3
      = check_box_tag :agree_service, '1', false, class: 'mr-2', data: { action: 'change->school-profile#agreeTermsAndConditionsChanged' }
      == t('school.profile.tests.agree_to_terms', link: link_to(t('school.profile.tests.terms_and_conditions'), "https://lingutesten.no/betingelser", target: '_blank', class: 'ml-1 mr-1'))
      = hidden_field_tag 'lingutest_enabled', true
    .enable-test-btn
      = submit_tag t('school.profile.tests.enable_test'), class: 'btn btn-primary btn-lg', disabled: 'disabled', data: { target: 'school-profile.enableTestBtn' }

app/views/school/current_teams/edit.js.erb
$("#school-main-modal").html("<%= j render 'school/current_teams/profile_form', team: team, country_by_ip: country_by_ip %>");
$("#school-main-modal").modal('show');

app/views/school/current_teams/enable_tests.js.erb
$("#school-main-modal").find('#tests-panel').html("<%= j render partial: 'school/current_teams/tests_profile', locals: { team: team } %>");

app/views/school/current_teams/form_submit.js.erb
$("#school-main-modal").modal('hide');
window.location.reload();