config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'
require 'subdomain_constraint'
require 'user_role_constraint'

Sidekiq::Web.app_url = '/'

Rails.application.routes.draw do
  mount API::Base => '/'
  mount GrapeSwaggerRails::Engine => '/documentation'

  get '/auth/google_user/callback', to: 'omniauth#create'
  get '/auth/*_student/callback', to: 'students/omniauth#create'
  scope constraints: SubdomainConstraint.new('admin', 'teach', 'school') do
    devise_for :users,
               controllers: { registrations: 'registrations', sessions: 'sessions' },
               path_names: { registration: 'register' }
  end
  mount Shrine.upload_endpoint(:cache) => '/upload', as: :upload

  scope constraints: SubdomainConstraint.new('teach') do
    scope module: :teach do
      get '/', to: 'lessons#index'
    end
    namespace :teach, path: '' do
      get '/dashboard', to: 'lessons#index', as: :dashboard
      resources :lessons do
        collection do
          get :draft
          get :pending
          get :approved
          get :published
          get :reviewable
          get :search
        end
        member do
          get :review
          post :publish
          post :status
          post :unpublish

          # TODO: move next 2 methods to separate controller
          post :add_objective
          post :set_color
          delete :remove_objective

          resource :lesson_split, only: [:new, :create]
          resource :task_move, only: [:new, :create]
        end
        resources :tasks do
          member do
            patch :position
            patch :toggle_published
            delete :delete_file_attachment
            get :convert_text_task_type, as: 'convert_type'
          end
        end
        resources :phrases, only: %i[index create destroy] do
          collection do
            post :generate
            delete :destroy_batch
          end
        end
        resources :reviews, only: %i[index create destroy]
      end

      resources :tasks do
        resources :items, only: %i[index create destroy update] do
          resources :words, only: %i[index create destroy]

          member do
            patch :move_up
            patch :move_down
          end
        end
      end
      scope module: :tasks, path: 'tasks/:task_id', as: :task do
        resource :preview, only: :show
      end

      resources :items, only: [] do
        resources :options, only: %i[create update destroy] do
          put :toggle_correct, on: :member
        end
      end

      resource :current_team, only: :create
      resources :teams, only: %i[new create edit update destroy] do
        member do
          post :default
          get :followers
          get :instruction
          post 'instruction' => 'teams#instruction_post'
        end

        resources :team_users, path: 'members', only: %i[index update destroy] do
          member do
            delete :leave
          end
        end

        resources :team_domains, only: %i[create destroy]
      end

      resources :posts
      resources :courses do
        get :words, on: :member
        resources :course_sections, as: :sections, only: %i[create update destroy] do
          member do
            post :add_lesson
            get :remove_lesson
            patch :move_up
            get :move_up_lesson
            get :move_down_lesson
          end
        end
      end
    end
  end
  resource :profile, only: %i[show update] do
    patch :update_password
    get :incomplete
  end

  scope constraints: SubdomainConstraint.new('admin') do
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
    scope module: :admin do
      get '/', to: 'dashboard#index'
    end
    namespace :admin, path: '' do
      scope constraints: UserRoleConstraint.new(:admin, :editor) do
        resources :dashboard, only: :index
        resources :lessons, only: %i[index edit update show]
        resources :courses, only: %i[index show] do
          member do
            get :words
            get :level_words
            put :translate_words
          end

          collection do
            get :reset_phrases_count
          end
        end
        resources :skills, only: %i[index create show update]
        resources :teams, except: :destroy
        resources :users
        resources :students
        resources :rewards
        resources :crawlers
        resources :search, only: :index
        resources :languages, only: [:index, :edit, :update] do
          get :inactive, on: :collection
          post :add_character, on: :member
          delete :remove_character, on: :member
          scope module: 'dictionary/languages' do
            resources :words do
              collection do
                delete :destroy_multiple
                get :remove_from_collection
                get :csv_import
                post 'csv_import' => 'words#csv_import_post'
                post :text_import
                post :recalculate_frequency
                get :search
                get :add_to_collection
                post 'add_to_collection' => 'words#add_to_collection_post'
              end

              member do
                get :edit_translation
                put :update_translation
              end
            end
            resources :collections do
              put :translate_words, on: :member
            end
          end
        end
        resources :teams do
          scope module: 'teams' do
            scope module: 'oauth', path: '' do
              resources :apps, path: 'oauth_apps', only: [:index, :show, :update, :destroy], as: :oauth_apps do
                put :regenerate_key, on: :member
              end
            end
          end

          member do
            post :signin_school
          end
        end
        resources :plans
      end
      match '/*any', via: :all, to: redirect(subdomain: 'teach', path: '/')
    end
  end
  resource :profile, only: %i[show update] do
    patch :update_password
  end

  scope constraints: SubdomainConstraint.new('school') do
    scope module: :school do
      get '/', to: 'dashboard#index'
    end

    namespace :school, path: '' do
      get '/dashboard', to: 'dashboard#index', as: :dashboard
      resource :gdpr_agreement, only: :show
      resource :dashboard, only: :index do
        collection do
          post :agreement
        end
      end
      resource :current_team, only: [:create, :edit, :update] do
        get :set, as: :set_team, to: 'current_teams#create'
      end
      resources :team_students, as: :students, except: [:create] do
        member do
          get :archive
          post :assign_team_group
          get :move_class
          delete :revoke_team_group
          get :lessons
          get :search_lessons
          post :assign_lessons
          get :restore_student
          get :remove_student
          get :courses
          get :build_language
          get :remove_language
          get :assign_course
          post :assign_course
        end

        collection do
          get :archived_students
          get :clear_archive
          get :import_students
          post :analyze_imported_file
          post :create_batch
          get  :invite_students
          post :send_invitations
          get :available_languages
        end

        resources :activities
      end
      post 'school_students', to: 'team_students#create', as: 'create_students'
      resources :team_groups do
        member do
          get :edit_plan
          put :archive
          put :update_plan
          get :toggle_joinable
          get :assign_course
          post :assign_course
        end
      end
      resources :team_users do
        member do
          get :activities
        end
        collection do
          get  :import_team_users
          post :analyze_imported_file
          post :create_batch
        end
      end
      resources :team_students, only: [] do
        resources :licenses, only: [:create, :update, :destroy] do
          collection do
            get :revoke_license
          end
          put :remove_end_date, on: :member
        end
      end
      resources :lessons
      resources :assignments, as: :documents
      resources :comments do
        post :add_comments, on: :member
        post :document_content_update, on: :collection
      end
      resources :school_assignments, as: :assignments do
        member do
          get :assign_student
          post 'assign_student' => 'school_assignments#assign_student_post'
          get :review
        end
      end
      resources :tests
      resources :activities do
        collection do
          get :activity_logs
        end
        member do
          put :undo_activity
        end
      end
      resources :oauth_apps do
        member do
          put :refresh_secret
        end
      end
      resource :user, only: [:edit, :update], as: :current_profile
      resources :courses, only: [:index, :show] do
        member do
          get :assign_team_group
          post :assign_team_group
        end
        resources :course_sections, only: :show do
          member do
            get :change_view_mode
          end
        end
      end
      get 'search', to: 'search#index', as: :search
      get 'mobile', to: 'mobile#index', as: :mobile
    end
  end

  resources :teams, only: [] do
    resource :team_invitations, path: 'join'
  end

  resources :team_domain_invitations, only: [] do
    patch :accept
    patch :decline
  end

  devise_for :students
  root to: 'students/lessons#index'
  namespace :students, path: '' do
    scope path: 'invitation/:team_id' do
      resource :invitations, path: '', as: :invitation, only: :show do
        post :join, on: :member
      end
    end
    resources :courses, only: %i[show]
    resources :lessons do
      member do
        get 'play(/*any)' => '/static#index'

app/controllers/school/activities_controller.rb
# frozen_string_literal: true

module School
  class ActivitiesController < ApplicationController
    def index
      authorize_action
      if params[:student_id].present?
        activities = Activity.by_team_student(team_student).page(params[:page])
        render :student_activities, locals: { student: student, activities: activities }
      else
        activities = Activity.by_team_user(team_user).page(params[:page])
        render :team_user_activities, locals: { team_user: team_user, activities: activities }
      end
    end

    def activity_logs
      authorize_action
      collection = Activity.by_team(current_team.id).includes(:owner, :recipient, :trackable).distinct.page(params[:page])
      @search = collection.ransack(params[:q])
      render :activity_logs, locals: { activities: @search.result, owners: current_team.team_users }
    end

    def undo_activity
      authorize_action(activity)
      result = School::UndoActivityService.call(current_team: current_team, activity: activity, current_user: current_user)
      if result[:errors].blank?
        redirect_to activity_logs_school_activities_path
      else
        redirect_to activity_logs_school_activities_path, notice: result[:errors][0]
      end
    end

    private

    def activity
      @activity ||= Activity.find(params[:id])
    end

    def student
      @student ||= Student.find(params[:student_id])
    end

    def team_user
      @team_user ||= TeamUser.find(params[:team_user_id])
    end

    def team_student(current_student = student)
      current_team.team_students.find_by(student: current_student)
    end
    helper_method :team_student

    def authorize_action(record = Activity)
      authorize(record, "#{action_name}?", policy_class: policy_class)
    end

    def policy_class
      School::ActivityPolicy
    end
  end
end

app/controllers/school/application_controller.rb
# frozen_string_literal: true

module School
  class ApplicationController < ::ApplicationController
    include PasswordGenerator
    include UserControllerContext
    include IncompleteProfileChecker
    before_action :authenticate_user!

    layout 'school/school'

    def policy(record)
      super([:school, record])
    end

    def pundit_user
      current_team_user
    end

    def current_team_user
      return if current_user.blank? || current_team.blank?

      @current_team_user ||= current_user.team_users.find_by(team_id: current_team&.id)
    end
    helper_method :current_team_user

    def redirect_onboarding(team = current_team)
      return if team.abilities.present?
      return unless current_team_user.owner?

      redirect_to instruction_teach_team_path(team, refer: request.referer)
    end

    def gdpr_consented?
      render 'school/shared/gdpr_consenter' unless current_team.gdpr_consented?
      current_team.gdpr_consented?
    end
  end
end

app/controllers/school/assignments_controller.rb
# frozen_string_literal: true

module School
  class AssignmentsController < ApplicationController
    def index
      authorize_action
      @search = scope.ransack(params[:q])
      assignments_stats = AssignmentsStats.stats(scope, current_team)
      render :index, locals: { documents: @search.result, assignments_stats: assignments_stats }
    end

    def show
      authorize_action(document)
      comment = comment_scope.new(commentable: document)
      render :show, locals: { document: document, comment: comment, comments: document.comments.order(created_at: :asc) }
    end

    private

    def scope
      policy_scope(document_scope, policy_scope_class: School::AssignmentPolicy::Scope)
    end

    def document_scope
      Document.where(team: current_team)
    end

    def document
      @document = Document.find(params[:id])
    end

    def comment_scope
      current_user.comments
    end

    def policy_class
      School::AssignmentPolicy
    end

    def authorize_action(record = Student)
      authorize(record, "#{action_name}?", policy_class: policy_class)
    end
  end
end

app/controllers/school/comments_controller.rb
# frozen_string_literal: true

module School
  class CommentsController < ApplicationController
    def create
      comment = comments_scope.where(commentable: document).new(comment_params)
      if comment.save
        document.reviewed!
        School::DocumentMailer.with(comment: comment).new_document_comment.deliver_later
        render :create, locals: { comment: comment, document: document }
      else
        render 'school/assignments/show', locals: { document: document, comment: comment }
      end
    end

    def add_comments
      comment.comments[params[:word]] = params[:comment]
      comment.save
      render :add_comments, locals: { word: params[:word], comment: params[:comment], document_id: params[:document_id] }
    end

    def document_content_update
      document.update(comment_contents: params[:content])
      render json: { success: true }
    end

    private

    def policy_class
      School::CommentPolicy
    end

    def authorize_action(record = Comment)
      authorize(record, "#{action_name}?", policy_class: policy_class)
    end

    def comment
      @comment ||= Comment.find(params[:id])
    end

    def document
      @document ||= Document.find(params[:document_id])
    end

    def comments_scope
      current_user.comments
    end

    def comment_params
      params.require(:comment).permit(:content, :audio)
    end
  end
end

app/controllers/school/course_sections_controller.rb
# frozen_string_literal: true

module School
  class CourseSectionsController < ApplicationController
    layout 'school/empty'

    def show
      authorize_action
      render_show
    end

    def change_view_mode
      authorize_action
      current_user.update(table_view: params[:table_view_mode])
      render_show
    end

    def render_show
      render :show, locals: {
        course: course,
        course_section: course_section,
        lessons: lessons,
        table_view: current_user_table_view
      }
    end

    private

    def lessons
      course_section.lessons.kept.published
    end

    def current_user_table_view
      current_user.table_view.presence || 'list'
    end

    def course_section
      @course_section ||= scope.find(params[:id])
    end

    def course
      course_section.course
    end

    def authorize_action(record = Course)
      authorize(record, "#{action_name}?", policy_class: policy_class)
    end

    def policy_class
      School::CourseSectionPolicy
    end

    def scope
      policy_scope(CourseSection, policy_scope_class: School::CourseSectionPolicy::Scope)
    end
  end
end

app/controllers/school/gdpr_agreements_controller.rb
# frozen_string_literal: true

module School
  class GdprAgreementsController < ApplicationController
    def show
      render :show, locals: { team: GlobalID::Locator.locate_signed(params[:team]),
                              processor_name: params[:processor_name] }, layout: false
    end
  end
end

app/controllers/school/mobile_controller.rb
# frozen_string_literal: true

module School
  class MobileController < ApplicationController
    skip_before_action :authenticate_user!

    layout 'school/blank'

    def index
      render :index
    end
  end
end

app/views/school/course_sections/_lessons.html.slim
- is_card_view = table_view == 'card'
.course-section-lessons
  .d-flex.align-items-center.justify-content-between.mb-3
    div.font-weight-semi-bold
      = t('shared.count_lessons', count: course_section.lessons.kept.published.count)
    .lessons-table-mode.d-flex
      = link_to change_view_mode_school_course_course_section_path(course, course_section, table_view_mode: 'list'), class: "btn p-1 shadow-none #{!is_card_view ? 'active' : ''}"
        = image_tag('icons/list-view.svg')
      = link_to change_view_mode_school_course_course_section_path(course, course_section, table_view_mode: 'card'), class: "btn p-1 ml-2 shadow-none #{is_card_view ? 'active' : ''}"
        = image_tag('icons/grid-view.svg')
  = render 'lessons_list', lessons: lessons, table_view: table_view

app/views/school/course_sections/_lessons_card_item.html.slim
.section-lesson-card-item.cursor-pointer
  .card-item-wrapper.h-100.d-flex.flex-column
    = lesson.image ? image_tag(lesson.image_url(:card_image), class: 'lesson-image w-100') : image_tag('uploader/defaults/lesson/original.png', class: 'lesson-image bg-400 w-100')
    .lesson-item-header.mt-3.d-flex.align-items-center
      = image_tag('icons/clock.svg', class: 'mr-1')
      span.mr-4
        = lesson.average_duration ? lesson.average_duration_human : '0 m'
      = image_tag('icons/message-circle.svg', class: 'mr-1')
      span.mr-4
        = t('teach.course_sections.lesson_row.word_count', count: lesson.phrases_count)
      = image_tag('icons/star.svg', class: 'mr-1')
      span
        span= lesson.rating.to_i
        span.text-500=< "(#{lesson.ratings_count})"
    h5.lesson-title.font-weight-semi-bold.mt-2
      = lesson.title
    .lesson-category-skills.d-flex.flex-column.justify-content-between
      - if lesson.tags.reject(&:empty?).any?
        .d-flex.align-items-center.flex-wrap.mt-3
          == lesson_tags_container(lesson.tags.reject(&:empty?), 'category')
      - if lesson.skills.any?
        .d-flex.align-items-center.flex-wrap.mt-2
          == lesson_tags_container(lesson.skills.map(&:name), 'skill')
      p.fs--1.mt-3
        - if lesson.objectives.blank?
          span.text-danger= t('teach.reviews.index.no_learning_objectives')
        - else
          - lesson.objectives.each_with_index do |objective, i|
            = "#{i + 1}. #{objective}"
            br
      .lesson-author
        span.text-500
          = "#{t('created_by')}:"
        =< lesson.author_name
    .lesson-item-actions.mt-3.collapse
      .d-flex.justify-content-between
        button.btn.btn-primary.mr-2.d-inline-flex.align-items-center.px-2 data-toggle='tooltip' data-placement='bottom' title=t('shared.available_date')
          = image_tag('icons/classroom.svg', class: 'mr-1')
          = t('school.course_sections.classroom')
        = link_to students_lesson_url(lesson, subdomain: nil, host: ENV.fetch('MAIN_HOST', 'lingu.com')), class: 'btn btn-primary d-inline-flex align-items-center px-2' do
          = image_tag('icons/self-study.svg', class: 'mr-1')
          = t('school.course_sections.self_study')

app/views/school/course_sections/_lessons_list.html.slim
div class="section-lessons-#{table_view}-container"
  = render partial: "lessons_#{table_view}_item", collection: lessons, as: :lesson, cached: true
  - if table_view == 'card'
    == empty_lesson_cards(lessons.count)

app/views/school/course_sections/_lessons_list_item.html.slim
.section-lesson-list-item.w-100.d-flex
  = lesson.image ? image_tag(lesson.image_url(:card_image), class: 'lesson-image') : image_tag('uploader/defaults/lesson/original.png', class: 'lesson-image bg-400')
  .ml-4.w-100
    .lesson-item-header.d-flex.align-items-center.justify-content-between
      .d-flex.align-items-center
        = image_tag('icons/clock.svg', class: 'mr-1')
        span.mr-4
          = lesson.average_duration ? lesson.average_duration_human : '0 m'
        = image_tag('icons/message-circle.svg', class: 'mr-1')
        span.mr-4
          = t('teach.course_sections.lesson_row.word_count', count: lesson.phrases_count)
        = image_tag('icons/star.svg', class: 'mr-1')
        span
          span= lesson.rating.to_i
          span.text-500=< "(#{lesson.ratings_count})"
      div
        span.text-500
          = "#{t('created_by')}:"
        =< lesson.author_name
      .lesson-item-actions
        button.btn.btn-primary.mr-2.d-inline-flex.align-items-center data-toggle='tooltip' data-placement='bottom' title=t('shared.available_date')
          = image_tag('icons/classroom.svg', class: 'mr-1')
          = t('school.course_sections.classroom')
        a.btn.btn-primary.d-inline-flex.align-items-center href="https://lingu.com/lessons/#{lesson.id}"
          = image_tag('icons/self-study.svg', class: 'mr-1')
          = t('school.course_sections.self_study')
    h5.font-weight-semi-bold.mt-2
      = lesson.title
    p.fs--1.mt-3
      - if lesson.objectives.blank?
        .text-danger= t('teach.reviews.index.no_learning_objectives')
      - else
        - lesson.objectives.each_with_index do |objective, i|
          = "#{i + 1}. #{objective}"
          br
    .lesson-category-skills.d-flex
      - if lesson.tags.reject(&:empty?).any?
        .mr-3.d-flex.align-items-center
          == lesson_tags_container(lesson.tags.reject(&:empty?), 'category')
      - if lesson.skills.any?
        .d-flex.align-items-center
          == lesson_tags_container(lesson.skills.map(&:name), 'skill')

app/views/school/course_sections/show.html.slim
- set_page_title course.title
.school-course-container.d-flex.flex-column.min-vh-100
  = render 'school/courses/course_header', course: course
  .course-info.flex-grow-1.d-flex
    .w-25
      = render 'school/courses/course_overview_list', course: course, course_section: course_section
    .w-75
      = render 'lessons', course: course, course_section: course_section, table_view: table_view, lessons: lessons